control-service: produce seruce base job images for python 3.8-3.11
Signed-off-by: Stefan miroslavi@vmware.com

diff --git a/projects/control-service/projects/job-base-image-secure/Dockerfile-data-job-base b/projects/control-service/projects/job-base-image-secure/Dockerfile-data-job-base
--- a/projects/control-service/projects/job-base-image-secure/Dockerfile-data-job-base
+++ b/projects/control-service/projects/job-base-image-secure/Dockerfile-data-job-base
@@ -1,5 +1,96 @@
 # https://docs.docker.com/develop/develop-images/dockerfile_best-practices
-FROM photon:latest
+FROM photon:latest as builder
+
+ARG PYTHON_MAJOR
+ARG PYTHON_MINOR
+ARG PYTHON_PATCH
+ARG PYTHON_VERSION=${PYTHON_MAJOR}.${PYTHON_MINOR}.${PYTHON_PATCH}
+
+ARG _prefixdir=/usr/local
+ARG _bindir=${_prefixdir}/bin
+ARG _libdir=${_prefixdir}/lib
+ARG _workdir=/usr/src
+ARG _pylibdir=${_libdir}/python${PYTHON_MAJOR}.${PYTHON_MINOR}
+ARG _bytecode_suffixes=.cpython-*.pyc
+
+ENV PATH=${_bindir}:${PATH}
+WORKDIR ${_workdir}
+
+# Install build dependencies
+RUN yum install -y \
+    coreutils \
+    gcc \
+    glibc-devel \
+    binutils \
+    build-essential \
+    wget \
+    make \
+    gcc \
+    openssl-devel \
+    bzip2-devel \
+    libffi-devel \
+    zlib-devel
+
+# Extract python source
+RUN : \
+ && set -ex \
+ && curl -O https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz \
+ && tar -xvzf Python-${PYTHON_VERSION}.tgz \
+ && mv Python-${PYTHON_VERSION} python \
+ && rm Python-${PYTHON_VERSION}.tgz
+
+# Build and install python
+RUN : \
+ && set -ex \
+ && cd ${_workdir}/python \
+ && ./configure \
+        --enable-loadable-sqlite-extensions \
+        --enable-optimizations \
+        --enable-option-checking=fatal \
+        --enable-shared \
+        --with-lto \
+        --without-ensurepip \
+        --prefix=${_prefixdir} \
+        LDFLAGS=-Wl,-rpath=${_libdir} \
+ && make \
+ && make install
+
+# Make some useful symlinks
+RUN : \
+ && set -ex \
+ && cd ${_bindir} \
+ && ln -s python${PYTHON_MAJOR} python
+
+# Get and install pip
+RUN : \
+ && set -ex \
+ && curl -O https://bootstrap.pypa.io/get-pip.py \
+ && python get-pip.py \
+ && pip --version \
+ && rm -f get-pip.py
+
+# Cleanup files
+RUN : \
+ && set -ex \
+ && rm -rf \
+      ${_workdir}/python \
+      ${_pylibdir}/turtle.py \
+      ${_pylibdir}/__pycache__/turtle*${_bytecode_suffixes} \
+      ${_bindir}/idle* \
+      ${_pylibdir}/idlelib \
+      ${_pylibdir}/tkinter \
+      ${_pylibdir}/turtledemo \
+      ${_pylibdir}/ctypes/test \
+      ${_pylibdir}/distutils/tests \
+      ${_pylibdir}/lib2to3/tests \
+      ${_pylibdir}/sqlite3/test \
+      ${_pylibdir}/test \
+      ${_pylibdir}/tkinter/test \
+      ${_pylibdir}/unittest/test \
+ && find ${_pylibdir} -type d -name __pycache__ -exec rm -rf '{}' +
+
+FROM photon:latest as base-job-image
+COPY --from=builder /usr/local/ /usr/local/
 
 # Set the working directory
 WORKDIR /job
@@ -7,10 +98,5 @@ WORKDIR /job
 # Uninstall native dependencies
 RUN yum erase toybox -y
 
-# Install python
-RUN yum install python3-3.10.0-10.ph4 python3-pip-3.10.0-10.ph4 shadow -y
-RUN ln -fs /usr/bin/python3 /usr/local/bin/python
-
-# Install native dependencies so that requirements in requirements.txt can be installed
-# some (like openssl) should be pre-installed in the base image but let's be explicit
-RUN yum install build-essential -y
+# Install native dependencies
+RUN yum install shadow build-essential -y
